-- StudyLink demo schema. Use fictional records only.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  display_name text not null,
  grade_level int not null check (grade_level between 6 and 12),
  role text not null check (role in ('student', 'tutor', 'both')),
  subjects text[] default '{}',
  topics text[] default '{}',
  availability text default 'Demo availability'
);

alter table public.profiles add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.profiles add column if not exists username text;
create unique index if not exists profiles_user_id_key on public.profiles(user_id) where user_id is not null;
create unique index if not exists profiles_username_key on public.profiles(lower(username)) where username is not null;

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  tutor_id uuid references public.profiles(id),
  sender_id uuid references public.profiles(id),
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id),
  tutor_id uuid references public.profiles(id),
  topic text not null,
  status text not null default 'scheduled',
  starts_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.tutoring_requests (
  id bigint generated by default as identity primary key,
  student_id uuid references public.profiles(id) not null,
  tutor_id uuid references public.profiles(id) not null,
  topic text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'declined')),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;
alter table public.sessions enable row level security;
alter table public.tutoring_requests enable row level security;

-- Prototype policies allow demo reads/inserts only. Tighten these before production.
drop policy if exists "demo profiles readable" on public.profiles;
drop policy if exists "demo messages readable" on public.messages;
drop policy if exists "demo messages insertable" on public.messages;
drop policy if exists "demo sessions readable" on public.sessions;
drop policy if exists "signed in profiles insertable" on public.profiles;
drop policy if exists "own profiles editable" on public.profiles;
drop policy if exists "signed in messages insertable" on public.messages;
drop policy if exists "signed in requests insertable" on public.tutoring_requests;
drop policy if exists "request participants readable" on public.tutoring_requests;
create policy "demo profiles readable" on public.profiles for select using (true);
create policy "signed in profiles insertable" on public.profiles for insert with check (auth.uid() = user_id);
create policy "own profiles editable" on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "demo messages readable" on public.messages for select using (true);
create policy "signed in messages insertable" on public.messages for insert with check (auth.uid() = (select user_id from public.profiles where id = sender_id));
create policy "demo sessions readable" on public.sessions for select using (true);
create policy "signed in requests insertable" on public.tutoring_requests for insert with check (auth.uid() = (select user_id from public.profiles where id = student_id));
create policy "request participants readable" on public.tutoring_requests for select using (auth.uid() = (select user_id from public.profiles where id = student_id) or auth.uid() = (select user_id from public.profiles where id = tutor_id));

-- Fictional demo records for the StudyLink prototype.
insert into public.profiles (id, display_name, grade_level, role, subjects, topics, availability)
values
  ('00000000-0000-0000-0000-000000000001', 'Jordan Lee', 8, 'student', array['Math'], array['Linear equations'], 'Today after school'),
  ('00000000-0000-0000-0000-000000000002', 'Maya R.', 8, 'tutor', array['Math'], array['Algebra', 'Linear equations'], 'Available today'),
  ('00000000-0000-0000-0000-000000000003', 'Sam P.', 7, 'tutor', array['Math', 'Science'], array['Fractions', 'Atoms'], 'Tomorrow afternoon'),
  ('00000000-0000-0000-0000-000000000004', 'Alex T.', 8, 'tutor', array['English'], array['Writing', 'Evidence'], 'Weekday evenings'),
  ('00000000-0000-0000-0000-000000000005', 'David K.', 8, 'student', array['Science'], array['Atoms'], 'Today after school')
on conflict (id) do update set
  display_name = excluded.display_name,
  grade_level = excluded.grade_level,
  role = excluded.role,
  subjects = excluded.subjects,
  topics = excluded.topics,
  availability = excluded.availability;

insert into public.messages (tutor_id, sender_id, body)
select '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000001', 'I keep getting stuck when I move a number to the other side.'
where not exists (select 1 from public.messages where body = 'I keep getting stuck when I move a number to the other side.');

insert into public.messages (tutor_id, sender_id, body)
select '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000002', 'Hi! I can help you work through linear equations.'
where not exists (select 1 from public.messages where body = 'Hi! I can help you work through linear equations.');

insert into public.sessions (student_id, tutor_id, topic, status, starts_at)
select '00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', 'Linear equations', 'scheduled', now() + interval '1 day'
where not exists (select 1 from public.sessions where student_id = '00000000-0000-0000-0000-000000000001' and tutor_id = '00000000-0000-0000-0000-000000000002' and topic = 'Linear equations');
